QKEYLM:
  login: xxxxxxxxxx@yahoo.com
  password: xxxxxxxxxxxxxx
  host: https://www.qkenhanced.com.au
  page_token: /external/Authentication/SignIn?ReturnUrl=%2Fexternal%2FStar%2FSignIn%3Fwa%3Dwsignin1.0%26wtrealm%3Dhttps%253A%252F%252Fwww.qkenhanced.com.au%252FEnhanced.Eylm%252F
  page_wsingin: /Enhanced.Eylm/
  child_id: 11111111
  room_id: 22222222
  page_journal: /Enhanced.Eylm/Child/RedirectToPortfolio/11111111?RoomId=22222222
  page_journal_date: /Enhanced.Eylm/ProgramJournal/PrintView?date=
  child_name:
    - Adel
    - Oliver
Kinderloop:
  login: xxxxxxxxxx@yahoo.com
  password: xxxxxxxxxxxxxx
  host: https://app.kinderloop.com/api
  feed: /feed/parent/?offset=0&max=5
  feed_details: /post/
  child_id: 22222222
  child_name:
    - Adel
DB:
  driver: pdo_sqlite
  path: ../store/store.sqlite3
Mailer:
  host: localhost
  port: 25
  bcc:
    - xxxxxxxx@yahoo.com
    - yyyyyyyyyyyy@gmail.com
  bcc_name:
    - XXXX XXXXX
    - YYYY YYYYYY
  from: xxxxxxxxxx@yahoo.com
  from_name: Tiny Tots
  to: xxxxxxxxxx@yahoo.com
  to_name: Tiny Tots
  subject: Tiny Tots Daily Journal
TimeZone: Australia/Sydney
Dropbox:
  access_token: XXXXXXXXXXXXXXXXXXXXXXXXXXX
