QKEYLM:
  login: xxxxxxxxxx@yahoo.com
  password: xxxxxxxxxxxxxx
  host: https://www.qkenhanced.com.au
  page_token: /external/Authentication/SignIn?ReturnUrl=/external/Navigation/Enhanced
  page_wsingin: /webui/
  child_id: 13715106
  room_id: 3676407
  page_journal: /webui/ProgramJournal/RedirectToPJ?ChildId=13715106&RoomId=3676407
  child_name: Adel
DB:
  driver: pdo_sqlite
  path: ../store/store.sqlite3
Mailer:
  host: localhost
  port: 25
  to: peter_csaba@yahoo.com
  to_name: Csaba Peter
  from: peter_csaba@yahoo.com
  from_name: Csaba Peter
  subject: Tiny Tots Daily Journal
    
