QKEYLM:
  login: peter_csaba@yahoo.com
  password: 
  host: https://www.qkenhanced.com.au
  page_token: /external/Authentication/SignIn?ReturnUrl=/external/
  page_wsingin: /external/Navigation/Enhanced
  page_webui: /webui/
  page_journal: /webui/ProgramJournal/RedirectToPJ?ChildId=13715106&RoomId=3676407
  child_name: Adel
  child_id: 13715106
  room_id: 3676407
DB:
  driver: pdo_sqlite
  path: ../store/store.sqlite3
Mailer:
  host: gmail-smtp-in.l.google.com
  port: 25
  to: john@doe.com
  to_name: John Doe
  from: john@doe.com
  from_name: John Doe
  subject: Version number changed
  body: \{body\}
    
